import{S as h,a as c,i as l}from"./assets/vendor-c493984e.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();document.querySelector(".loader");let p=new h(".gallery a");const d=document.querySelector(".img-list");function g(s){const o=s.hits.map(e=>`<li class="list-el">
                <a href="${e.largeImageURL}"><img src='${e.webformatURL}' alt='${e.tags}'></a>
                <div class="content">
                    <div class="item"><h3>Likes</h3><p>${e.likes}</p></div>
                    <div class="item"><h3>Views</h3><p>${e.views}</p></div>
                    <div class="item"><h3>Comments</h3><p>${e.comments}</p></div>
                    <div class="item"><h3>Downloads</h3><p>${e.downloads}</p></div>
                </div>
            </li>`).join("");d.textContent="",d.insertAdjacentHTML("beforeend",o),n(),p.refresh()}async function u(s){c.defaults.baseURL="https://pixabay.com";const o={key:"44349742-ecc8a7b60aea5585f0c207813",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0};try{return(await c.get("/api/",{params:o})).data}catch(e){console.log(e)}}u("dog");const m=document.querySelector(".form-el"),y=document.querySelector(".img-list"),f=document.querySelector(".loader");function L(){f.classList.remove("visually-hidden")}function n(){f.classList.add("visually-hidden")}m.addEventListener("submit",s=>{s.preventDefault();const o=m.elements[0].value.trim();if(L(),o)u(o).then(e=>{if(e.hits.length===0)throw n(),y.innerHTML="",new Error("Error! Nothing to load");g(e)}).catch(e=>{l.show({title:"Sorry",message:"there are no images matching your search query. Please try again!",color:"red"})});else{n(),l.error({message:"Info Search input must be filled!"});return}});
//# sourceMappingURL=commonHelpers.js.map
